#!/usr/bin/env bash
# Installs Gamerack for the current user only. Nothing is written system-wide.
#
# The program is copied to ~/.local/lib/gamerack, not linked to this folder:
# an installed application must not break because its source directory was
# renamed, moved or deleted. Your library, settings and covers live elsewhere
# again (~/.local/share and ~/.config) and are never touched by install or
# uninstall.
set -euo pipefail

SOURCE_DIR="$(dirname "$(readlink -f "$0")")"
LIB_DIR="${HOME}/.local/lib/gamerack"
BIN_DIR="${HOME}/.local/bin"
APP_DIR="${HOME}/.local/share/applications"
DESKTOP_FILE="${APP_DIR}/io.github.tketchup.Gamerack.desktop"

if [ "${1:-}" = "--uninstall" ]; then
  rm -rf "$LIB_DIR"
  rm -f "${BIN_DIR}/gamerack" "$DESKTOP_FILE"
  update-desktop-database "$APP_DIR" 2>/dev/null || true
  echo "Entfernt. Deine Bibliothek und Einstellungen sind geblieben:"
  echo "  ~/.local/share/gamerack/   Spiele, Cover und Verlauf"
  echo "  ~/.config/gamerack/        Einstellungen"
  exit 0
fi

if [ ! -d "${SOURCE_DIR}/gamerack" ]; then
  echo "Fehler: ${SOURCE_DIR}/gamerack nicht gefunden." >&2
  exit 1
fi

mkdir -p "$LIB_DIR" "$BIN_DIR" "$APP_DIR"

# Replace the installed copy wholesale, so a file deleted upstream does not
# survive as a leftover in the installation.
rm -rf "${LIB_DIR:?}/gamerack"
cp -r "${SOURCE_DIR}/gamerack" "${LIB_DIR}/gamerack"
find "${LIB_DIR}" -name "__pycache__" -type d -prune -exec rm -rf {} + 2>/dev/null || true

cat > "${BIN_DIR}/gamerack" <<EOF
#!/usr/bin/env bash
# Generated by install.sh — runs the installed copy, not a source folder.
export PYTHONPATH="${LIB_DIR}\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m gamerack "\$@"
EOF
chmod +x "${BIN_DIR}/gamerack"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Gamerack
Comment=Deine Spielebibliothek für Linux
Exec=${BIN_DIR}/gamerack
Icon=applications-games
Terminal=false
Categories=Game;
Keywords=Spiele;Games;Bibliothek;Library;Steam;Heroic;
StartupNotify=true
# Gamerack scans .desktop files; it must not list itself as a game.
NoDisplay=false
X-Gamerack-Self=true
EOF

update-desktop-database "$APP_DIR" 2>/dev/null || true

VERSION="$(python3 -c "import sys; sys.path.insert(0, '${LIB_DIR}'); import gamerack; print(gamerack.__version__)" 2>/dev/null || echo "?")"
echo "Gamerack ${VERSION} installiert."
echo "  Start:     gamerack   (oder über das Anwendungsmenü)"
echo "  Programm:  ${LIB_DIR}/gamerack"
echo "  Starter:   ${BIN_DIR}/gamerack"
echo "  Eintrag:   ${DESKTOP_FILE}"
echo
echo "Der Quellordner wird nicht mehr gebraucht. Nach Änderungen daran erneut"
echo "ausführen, um die installierte Fassung nachzuziehen. Entfernen mit:"
echo "  ${SOURCE_DIR}/install.sh --uninstall"
if ! echo ":$PATH:" | grep -q ":${BIN_DIR}:"; then
  echo
  echo "Hinweis: ${BIN_DIR} liegt nicht in deinem PATH."
fi
